### ISSUE TITLE
HI.解密加密数据的时候报illegal base64 data at input byte 0

### ISSUE THREAD

**Issue by yfeng** [aimuz/wechat-sdk#5]
登录的时候 解密加密数据的时候报illegal base64 data at input byte 0 你有遇到过吗？

**Comment by aimuz** [comment]
一般这个情况是加密向量非法，能否发一下复现代码 在2018年11月25日 22:50，大象爱吃鱼 写道： 登录的时候 解密加密数据的时候报illegal base64 data at input byte 0 你有遇到过吗？ — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by aimuz** [comment]
小程序登录还是公众号登录呢 在2018年11月26日 16:58，Aimuz me 写道： 一般这个情况是加密向量非法，能否发一下复现代码 在2018年11月25日 22:50，大象爱吃鱼 写道： 登录的时候 解密加密数据的时候报illegal base64 data at input byte 0 你有遇到过吗？ — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by aimuz** [comment]
问题是否已经搞定呢，搞定了我将关闭问题

**Comment by ring0li** [comment]
我也遇到了呢，奇怪，研究半天了。。。
